// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AssetsDialog: typeof import('./components/global/walletHead/assetsDialog.vue')['default']
    VueCountTo: typeof import('./components/global/vue-countTo.vue')['default']
    WallDialog: typeof import('./components/global/walletHead/wallDialog.vue')['default']
    WalletHead: typeof import('./components/global/walletHead.vue')['default']
  }
}

export { }
